#!/bin/sh
#
# @name TANDEM_x_tailsitter
#
# @type VTOL Quad Tailsitter
# @class VTOL
#
# @maintainer Roman Bapst <roman@px4.io>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults


param set-default PWM_MAIN_MAX 2000
param set-default PWM_MAIN_RATE 400

param set-default VT_MOT_ID 1234
param set-default VT_IDLE_PWM_MC  1080
param set-default VT_TYPE 0
param set-default VT_ELEV_MC_LOCK 1
param set-default COM_VEHICLE_ID 10
param set-default TD_GND_I_LOCK 1
param set-default TD_GND_THR_REL 0.55
param set-default TD_TIP_IDLE_PWM 1400
param set-default TD_TIP_P_FF 0.0
param set-default TD_MC_HOV_P 87.0
param set-default TD_MC_YAW_MAIN 0.30
param set-default TD_TIP_YAW_REV 1
param set-default COM_DISARM_PRFLT -1
param set-default FW_MAN_R_MAX 15
param set-default FW_MAN_P_MAX 10
param set-default FW_RR_P 0.05
param set-default FW_RR_I 0.04
param set-default FW_RR_FF 0.25
param set-default FW_RR_IMAX 0.15
param set-default FW_PR_P 0.07
param set-default FW_PR_I 0.04
param set-default FW_PR_FF 0.40
param set-default FW_PR_IMAX 0.20
param set-default FW_R_TC 0.5
param set-default FW_P_TC 0.5
param set-default FW_R_RMAX 45
param set-default FW_P_RMAX_POS 35
param set-default FW_P_RMAX_NEG 35
param set-default FW_R_LIM 25
param set-default FW_L1_PERIOD 20
param set-default FW_L1_DAMPING 0.8
param set-default FW_L1_R_SLEW_MAX 8
param set-default SENS_BOARD_ROT 24
set MAV_TYPE 20

# set MIXER TANDEM_x_vtol
set MIXER skip
set PWM_OUT 12345678

# . ${R}etc/init.d/rc.vtol_apps
