#!/bin/sh
#
# @name MeiYing WG15 VTOL
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output AUX1 Aileron 1
# @output AUX2 Elevator 1
# @output AUX3 Elevator 2
# @output AUX4 Rudder
# @output AUX5 Throttle
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults


param set-default PWM_AUX_DIS5 950
param set-default PWM_MAIN_RATE 400

param set-default VT_TYPE 2
param set-default VT_MOT_ID 123456
param set-default VT_FW_MOT_OFFID 123456
set MAV_TYPE 22

set MIXER my_wg15_vtol
# set hexa_x
set MIXER_AUX my_wg15_vtol

set PWM_OUT 12345678
