#!/bin/sh
#
# @name GuangHuan
#
# @type Standard Plane
# @class Plane
#
# @output MAIN1 aileron
# @output MAIN2 elevator
# @output MAIN3 throttle
# @output MAIN4 rudder
# @output MAIN5 flaps
# @output MAIN6 gear
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

param set-default PWM_AUX_RATE 50
param set-default PWM_MAIN_RATE 50

param set-default FW_AIRSPD_MIN 12
param set-default FW_AIRSPD_TRIM 19
param set-default FW_AIRSPD_MAX 35


param set-default COM_VEHICLE_ID 2

set MIXER AETRFG

# Rate must be set by group (see pwm info).
# Throttle is in the same group as servos.
